### ISSUE TITLE
Android.OS.NetworkOnMainThreadException, following this sample

### ISSUE THREAD

**Issue by RollsChris** [microsoftgraph/msgraph-sample-maui#123]
Hi, I am getting Android.OS.NetworkOnMainThreadException when trying to retrieve the users photo with this code:

```csharp
	_userPhoto = await graphClient.Me
	   .Photo
	   .Content
	   .GetAsync();
```

i cant figure out why any tips? 

this code runs before just fine: 

```csharp
   _user = await graphClient.Me.GetAsync(
       requestConfiguration =>
       {
           requestConfiguration.QueryParameters.Select =
               new[] { "displayName", "mail" };
       });
```

**Comment by jasonjoh** [comment]
Interesting. I found this issue: https://github.com/xamarin/xamarin-android/issues/5264. From reading through the comments, using `.ConfigureAwait` instead of `await` fixed the problem.

**Comment by RollsChris** [comment]
sorry just seen this, ill try that thanks ;)
