### ISSUE TITLE
Does not Work in Windows on Visual Studio 17.4

### ISSUE THREAD

**Issue by bfmyr4** [microsoftgraph/msgraph-sample-maui#42]
Runs and immediately exits. Output from debug:
"The program '[19916] GraphMAUI.exe: Program Trace' has exited with code 0 (0x0).
 The program '[19916] GraphMAUI.exe' has exited with code 3762504530 (0xe0434352)."

There is an issue with Visual Studio 17.4 about immediate exit that recommends a work around of adding "<WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>" to the .csproj. However, when this is done, it stops with an exception as follows:
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Source=GraphMAUI
  StackTrace:
   at GraphMAUI.WinUI.Program.XamlCheckProcessRequirements()
   at GraphMAUI.WinUI.Program.Main(String[] args) in C:\Users\brianmiller1\git\msgraph-sample-maui\GraphMAUI\obj\Debug\net7.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.g.i.cs:line 28

Clone solution, launch in windows.

**Expected behavior**
Launches normally.

**Desktop (please complete the following information):**
 - OS: Windows 10 (although a teammate is also having this problem on Windows 11).

**Comment by jasonjoh** [comment]
Sorry for the trouble @bfmyr4! I reproduce this with a fresh clone of the repo, but my existing clone (where I created the sample) works fine. Hopefully I can track this down, bear with me!

**Comment by jasonjoh** [comment]
I believe I've found the culprit: a missing launchSettings.json file. I was using an older .gitignore which excluded it. Can you try applying the changes from #43 locally (and undoing the change you made to your .csproj) and see if that resolves your error?

**Comment by bfmyr4** [comment]
That fixes it for me. Thanks.

**Comment by jasonjoh** [comment]
Thanks for confirming!
