### ISSUE TITLE
During signin is there a way to allow personal microsoft accounts?

### ISSUE THREAD

**Issue by dvaca-sml** [microsoftgraph/msgraph-sample-maui#55]
I registered the app in my personal azure account. But when I launch the app and I try to sign in I get the following error. 

'You can't sign in here with a personal account. Use your work or school account instead.'

Is there a way to modify the code or the app registration to allow sigin with per personal microsoft account?

**Comment by dvaca-sml** [comment]
That worked. Thanks!

**Comment by jasonjoh** [comment]
Great, glad that worked!
