### ISSUE TITLE
Build in Release mode never ending

### ISSUE THREAD

**Issue by drossoft** [microsoftgraph/msgraph-sample-maui#68]
Building solution in Release mode never ends when Microsoft.Graph 5.X is referenced.

1. Download this repo
2. Switch from Debug to Release
3. Build the solution

Expected behavior
The compilation of the solution finishes.

Tested with "Windows Machine" and also "Android Emulator", in both cases, it never ends.

**Comment by drossoft** [comment]
Thanks @jasonjoh. I can't publish my app because of this. I've downgraded Microsoft.Graph to 4.1 and it builds, and works properly on Windows, but not on Android, so haven't found a solution to connect my MAUI app to OneDrive.

The alternative is to switch to Google Drive, but I prefer to stick with OneDrive.

**Comment by andrueastman** [comment]
This should be resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2182 and release https://www.nuget.org/packages/Microsoft.Graph/5.32.0

**Comment by jasonjoh** [comment]
Confirmed!

```
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 12:24 PM and took 08:08.644 minutes ==========
```
